baseurl = "https://www.codevamping.com"
title = "Code Vamping"
canonifyurls = true
paginate = 3

theme = "vellichor"

googleAnalytics= "UA-129577406-1"

[author]
    name = "Mark Hollomon"
    email = "mhhollomon@gmail.com"

[social]
    github = "mhhollomon"
    linkedin = "in/markhollomon"

[params]
    headerImage = "img/bass_header.png"
    showReadTime = false
    postDateFormat = "2006-01-02"
    blogWelcome = "Blog Posts"

[taxonomies]
    tag = "tags"
    archive = "archives"

[menu]

    [[menu.topbrand]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = -110

    [[menu.topbrand]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = -100
