theme : "minimalist"

baseurl : "https://www.codevamping.com/"
languageCode : "en-us"
title : "Code Vamping"

# Define how many pages appear per site
paginate : 10

# Enable comments powered by Disqus by entering your disqus shortname
#disqusShortname : "spf13"

# Enable gogle analytics by entering your tracking code
googleAnalytics : ""

permalinks:
    post : "/:year/:month/:filename"

params:
    site_author : "Mark Hollomon"
    site_description : "Code Vamping - A (mostly) software development blog with music thrown in for spice"
    # Link custom assets relative to /static
    avatar : "img/profile-image.png"
    header_background : "img/bass_header_narrow.jpg"
    header_title : "Code Vamping"
    copyright : "Powered by [Hugo](http://gohugo.io)."
    custom_css : []
    custom_js  : []

    # Define which content types are shown on the homepage
    mainSections : ["post", "page"]

    # Enable gogle analytics by entering your tracking code
    google_analytics : ""

social :
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   : ""
    facebook  : ""
    linkedin  : "markhollomon"
    stackoverflow : "10741691/mhhollomon"
    behance   : ""
    dribbble  : ""
    instagram : ""
    github    : "mhhollomon"
    gplus     : ""
