baseurl = "https://www.codevamping.com"
title = "Code Vamping"
author = "Mark Hollomon"
canonifyurls = true
paginate = 3

theme = "vellichor"

googleAnalytics= "UA-129577406-1"

[social]
    github = "mhhollomon"
    linkedin = "in/markhollomon"

[params]
    headerImage = "img/bass_header.png"
    showReadTime = false
    postDateFormat = "2006-01-02"
    blogWelcome = "Blog Posts"

[taxonomies]
    tag = "tags"
    archive = "archives"
