#!/usr/bin/env node

'use strict;'

const Purgecss = require("purgecss");
const fs = require("fs");
const path = require("path");

const config_filename = "./purgecss.config.js";

let filename = '-';

if (process.argv.length >= 3) {
    filename = process.argv[2];
}

let config;

if (fs.existsSync(config_filename)) {
    const t = path.join(process.cwd(), config_filename)
    config = require(t);
}

let stdin_string = fs.readFileSync(0).toString();

if (config == null) {
    config = { 
        css: [{ raw : stdin_string }],
        content : [ 'site/**/*.html' ] 
    };
} else {
    config.css = [{ raw : stdin_string }];
}


async function purge_it (config) {

    const purger = new Purgecss.PurgeCSS();
    console.log("got here ----");

    for (z of Object.getOwnPropertyNames(config)) {
        console.log(`${z} => ${config[z]}`);
    }
    let result = await purger.purge(config);
    if (filename == '-') {
        console.log(result[0].css);
    } else {
        fs.writeFile(filename, result[0].css, function(err) {
                        if (err) console.error(err.message)
                    })
    }
}

purge_it(config)
