name: build deploy firebase

on:
    repository_dispatch :
        branches: 
            - master

    push:
        branches: 
            - master


jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master
        
      - name: setup hugo
        uses: peaceiris/actions-hugo@master
        with:
          hugo-version: 'latest'
          extended: true

      - name: build
        run : |
            env
            npm install && npm run build:dist

      - name: deploy-to-firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
