name: build deploy firebase

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master
        
      - name: setup hugo
        uses: peaceiris/actions-hugo@master
        with:
          hugo-version: '0.61.0'
          extended: true

      - name: build
        run: hugo --minify
      
      - name: upload
        uses: actions/upload-artifact@master
        with:
          name: deploy-files
          path: public

  deploy:
    name: Deploy
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: download
        uses: actions/download-artifact@master
        with:
          name: deploy-files
          path: public

      - name: deploy-to-firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  mark-deploy:
    name: Mark Deploy
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name : generate_file
        run  : |
          hugo list future | cut -d',' -f2 | cut -dT -f1 | sort | head -1 > next_deploy_date.txt

      - name : setup-gcloud
        uses : GoogleCloudPlatform/github-actions/setup-gcloud@master
        with :
          version : '274.0.0'
          service_account_email: ${{secrets.GCP_GITHUB_FID}}
          service_accout_key: ${{secrets.GCP_GITHUB_KEY}}

      - name : upload_file
        run  : |
          gsutil cp next_deploy_date.txt gs://code-vamping.appspot.com
