name: schedule redeploy

on:
    repository_dispatch :
        types : [ "request_redeploy" ]

    push:
        branches: 
            - master
            - main

env :
    BUCKET_URI: "gs://redeploy-data.codevamping.com"
jobs:
  schedule-redeploy:
    name: Schedule Redeploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: setup hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: 'latest'
          extended: true

      - name : generate_file
        run  : |
          hugo list future | cut -d',' -f6 | sort | grep -v publishDate | head -1 > next_deploy_date.txt
          echo "Deploy date will be"
          cat next_deploy_date.txt
          echo "END"

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name : setup-gcloud
        uses : google-github-actions/setup-gcloud@v1

      - name : upload_file
        run  : |
          gsutil cp next_deploy_date.txt $BUCKET_URI
