name: build with grunt

on:
    push:
        branches: 
            - grunt

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master
        
      - name: setup hugo
        uses: peaceiris/actions-hugo@master
        with:
          hugo-version: '0.61.0'
          extended: true

      - name: build
        uses : elstudio/actions-js-build/build@master
